import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="border-b p-4 flex gap-4 text-sm">
          <Link href="/" prefetch={true}>
            Home
          </Link>
          <Link href="/uncached" prefetch={true}>
            /uncached
          </Link>
          <Link href="/allow-runtime" prefetch={true}>
            /allow-runtime
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
